/////////////////////////////////////////////////////////
//
//  Craftable Merchant Dialogs (CMD) by Festyx
//
//  Name:  me_cmdtesar
//
//  Generated by 'MerchantMaker'. A utility by Festyx.
//
/////////////////////////////////////////////////////////
#include "cnr_merch_utils"

void ProcessMenu_me_cmdtesar_0(string sMenu_me_cmdtesar_0);
void ProcessMenu_me_cmdtesar_1(string sMenu_me_cmdtesar_1);
void ProcessMenu_me_cmdtesar_2(string sMenu_me_cmdtesar_2);
void ProcessMenu_me_cmdtesar_3(string sMenu_me_cmdtesar_3);
void ProcessMenu_me_cmdtesar_4(string sMenu_me_cmdtesar_4);

void main()
{
  CnrMerchantSetMerchantGreetingText("me_cmdtesar", "Rad vykoupim vyrobky ze dreva..");
  CnrMerchantSetMerchantBuyText("me_cmdtesar", "Mate neco zajimaveho z tohoto seznamu?");
  CnrMerchantSetMerchantSellText("me_cmdtesar", "...");

  string sMenu_me_cmdtesar_0 = CnrMerchantAddSubMenu("me_cmdtesar", "Ostatni");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdtesar_0(sMenu_me_cmdtesar_0));

  string sMenu_me_cmdtesar_1 = CnrMerchantAddSubMenu("me_cmdtesar", "Šípy, šipky");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdtesar_1(sMenu_me_cmdtesar_1));

  string sMenu_me_cmdtesar_2 = CnrMerchantAddSubMenu("me_cmdtesar", "Luky");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdtesar_2(sMenu_me_cmdtesar_2));

  string sMenu_me_cmdtesar_3 = CnrMerchantAddSubMenu("me_cmdtesar", "Kuše");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdtesar_3(sMenu_me_cmdtesar_3));

  string sMenu_me_cmdtesar_4 = CnrMerchantAddSubMenu("me_cmdtesar", "Zbranì");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdtesar_4(sMenu_me_cmdtesar_4));
}

void ProcessMenu_me_cmdtesar_0(string sMenu_me_cmdtesar_0)
{
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Dlouhá dubová prkna", "cnrStaveLongOak", 5, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Dlouhá mahagonová prkna", "cnrStaveLongMah", 6, 6, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Dlouhá oøechová prkna", "cnrStaveLongHic", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Dubové døevo", "cnrBranchOak", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Krátká dubová prkna", "cnrStaveShortOak", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Krátká mahagonová prkna", "cnrStaveShortMah", 5, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Krátká oøechová prkna", "cnrStaveShortHic", 3, 3, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Násada dubová", "cnrShaftOak", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Násada mahagonová", "cnrShaftMahog", 2, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Násada oøechová", "cnrShaftHick", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Násada šipek (20)", "cnrShaftsBolt", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Násada šípù (20)", "cnrShaftsArrow", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Ocarovane dubove drevo", "me_dre_ocardub", 20, 20, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Ocarovane mahagonove drevo", "me_dre_ocarmah", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Ocarovane orechove drevo", "me_dre_ocarorech", 10, 10, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Oøechové døevo", "cnrBranchHic", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Prkno dubu", "cnrPlankOak", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Prkno mahagonu", "cnrPlankMah", 5, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Prkno oøechu", "cnrPlankHic", 3, 3, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_0, "Tìtiva luku", "cnrBowString", 2, 2, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdtesar_1(string sMenu_me_cmdtesar_1)
{
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, blesk", "cnrArrowLightng", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, bodnı", "cnrArrowPiercing", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, drtivı", "cnrArrowCrushing", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, hromovı", "cnrArrowThunder", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, jed", "cnrArrowPoison", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, kyselina", "cnrArrowAcid", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, led", "cnrArrowIce", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, obyèejnı", "cnrArrowPlain", 1, 1, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, oheò", "cnrArrowFire", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šíp, posvìcenı", "cnrArrowHoly", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, blesková", "cnrBoltLightng", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, bodající", "cnrBoltPiercing", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, drtivá", "cnrBoltCrushing", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, hrom", "cnrBoltThunder", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, jed", "cnrBoltPoison", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, kyselina", "cnrBoltAcid", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, ledová", "cnrBoltIce", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, obyèejná", "cnrBoltPlain", 1, 1, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, ohnivá", "cnrBoltFire", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_1, "Šipka, svatá", "cnrBoltHoly", 2, 2, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdtesar_2(string sMenu_me_cmdtesar_2)
{
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany dubovy dlouhy luk", "me_luk_ocdlOak", 750, 750, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany dubovy kratky luk", "me_luk_ockrMah", 745, 745, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany Mahagonovy dlouhy luk", "me_luk_ocdlMah", 2100, 2100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany orechovy dlouhy luk", "me_luk_ocdlHic", 480, 480, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany orechovy kratky luk", "me_luk_ockrHic", 476, 476, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany skladany dubovy dlouhy luk", "me_luk_COocdlOak", 892, 892, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany skladany dubovy kratky luk", "me_luk_COockrOak", 888, 888, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany skladany mahagonovy dlouhy luk", "me_luk_COocdlMah", 2335, 2335, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany skladany mahagonovy kratky luk", "me_luk_COockrMah", 2331, 2331, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany skladany orechovy dlouhy luk", "me_luk_COocdlHic", 595, 595, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Ocarovany skladany orechovy kratky luk", "me_luk_COockrHic", 591, 591, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Skládanı dubovı dlouhı luk", "cnrCoLongBowOak", 112, 112, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Skládanı dubovı krátkı luk", "cnrCoShortBowOak", 108, 108, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Skládanı mahagonovı dlouhı luk", "cnrCoLongBowMah", 834, 834, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Skládanı mahagonovı krátkı luk", "cnrCoShortBowMah", 829, 829, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Skládanı oøechovı dlouhı luk", "cnrCoLongBowHic", 35, 35, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Skládanı oøechovı krátkı luk", "cnrCoShortBowHic", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Dubovı dlouhı luk", "cnrLongBowOak", 53, 53, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Dubovı krátkı luk", "cnrShortBowOak", 63, 63, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Mahagonovı dlouhı luk", "cnrLongBowMah", 696, 696, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Mahagonovı krátkı luk", "cnrShortBowMah", 692, 692, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Oøechovı dlouhı luk", "cnrLongBowHic", 16, 16, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_2, "Oøechovı krátkı luk", "cnrShortBowHic", 12, 12, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdtesar_3(string sMenu_me_cmdtesar_3)
{
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Lehká dubová kuše", "cnrLightBowOak", 57, 57, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Lehká mahagonová kuše", "cnrLightBowMah", 549, 549, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Lehká oøechová kuše", "cnrLightBowHic", 12, 12, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Ocarovana Lehka dubova kuse", "me_kus_ockrOak", 597, 597, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Ocarovana Lehka mahagonova kuse", "me_kus_ockrMah", 1633, 1633, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Ocarovana Lehka orech kuse", "me_kus_ockrHic", 460, 460, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Ocarovana tezka dubova kuse", "me_kus_ocdlOak", 655, 655, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Ocarovana tezka mahagonova kuse", "me_kus_ocdlMah", 1727, 1727, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "Ocarovana tezka orechova kuse", "me_kus_ocdlHic", 511, 511, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "eká dubová kuše", "cnrHeavyBowOak", 77, 77, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "eká mahagonová kuše", "cnrHeavyBowMah", 605, 605, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_3, "eká oøechová kuše", "cnrHeavyBowHic", 28, 28, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdtesar_4(string sMenu_me_cmdtesar_4)
{
  CnrMerchantAddItem(sMenu_me_cmdtesar_4, "Døevìná hùl", "cnrQStaffWood", 1, 1, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_4, "Døevìná palice", "cnrClubWood", 1, 1, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdtesar_4, "Døevìné kopí", "cnrSpearWood", 1, 1, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}


