/////////////////////////////////////////////////////////
//
//  Craftable Merchant Dialogs (CMD) by Festyx
//
//  Name:  me_cmdpotravhar
//
//  Generated by 'MerchantMaker'. A utility by Festyx.
//
/////////////////////////////////////////////////////////
#include "cnr_merch_utils"

void ProcessMenu_me_cmdpotravhar_0(string sMenu_me_cmdpotravhar_0);
void ProcessMenu_me_cmdpotravhar_0_0(string sMenu_me_cmdpotravhar_0_0);
void ProcessMenu_me_cmdpotravhar_0_1(string sMenu_me_cmdpotravhar_0_1);
void ProcessMenu_me_cmdpotravhar_1(string sMenu_me_cmdpotravhar_1);
void ProcessMenu_me_cmdpotravhar_1_0(string sMenu_me_cmdpotravhar_1_0);
void ProcessMenu_me_cmdpotravhar_1_1(string sMenu_me_cmdpotravhar_1_1);
void ProcessMenu_me_cmdpotravhar_1_2(string sMenu_me_cmdpotravhar_1_2);
void ProcessMenu_me_cmdpotravhar_1_3(string sMenu_me_cmdpotravhar_1_3);
void ProcessMenu_me_cmdpotravhar_1_4(string sMenu_me_cmdpotravhar_1_4);
void ProcessMenu_me_cmdpotravhar_1_5(string sMenu_me_cmdpotravhar_1_5);
void ProcessMenu_me_cmdpotravhar_2(string sMenu_me_cmdpotravhar_2);
void ProcessMenu_me_cmdpotravhar_2_0(string sMenu_me_cmdpotravhar_2_0);
void ProcessMenu_me_cmdpotravhar_2_1(string sMenu_me_cmdpotravhar_2_1);
void ProcessMenu_me_cmdpotravhar_3(string sMenu_me_cmdpotravhar_3);
void ProcessMenu_me_cmdpotravhar_4(string sMenu_me_cmdpotravhar_4);
void ProcessMenu_me_cmdpotravhar_5(string sMenu_me_cmdpotravhar_5);

void main()
{
  CnrMerchantSetMerchantGreetingText("me_cmdpotravhar", "No pokud máte nìco co se hospodì hodí, tak to rad koupim.");
  CnrMerchantSetMerchantBuyText("me_cmdpotravhar", "No, tyhle vìci by se mnì hodily a rád bych je koupil.");
  CnrMerchantSetMerchantSellText("me_cmdpotravhar", "...");

  string sMenu_me_cmdpotravhar_0 = CnrMerchantAddSubMenu("me_cmdpotravhar", "Peèivo");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_0(sMenu_me_cmdpotravhar_0));

  string sMenu_me_cmdpotravhar_1 = CnrMerchantAddSubMenu("me_cmdpotravhar", "Suroviny");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_1(sMenu_me_cmdpotravhar_1));

  string sMenu_me_cmdpotravhar_2 = CnrMerchantAddSubMenu("me_cmdpotravhar", "Štávy a oleje");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_2(sMenu_me_cmdpotravhar_2));

  string sMenu_me_cmdpotravhar_3 = CnrMerchantAddSubMenu("me_cmdpotravhar", "Alkohol");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_3(sMenu_me_cmdpotravhar_3));

  string sMenu_me_cmdpotravhar_4 = CnrMerchantAddSubMenu("me_cmdpotravhar", "Maso");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_4(sMenu_me_cmdpotravhar_4));

  string sMenu_me_cmdpotravhar_5 = CnrMerchantAddSubMenu("me_cmdpotravhar", "Mám tu òákı hlavy");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_5(sMenu_me_cmdpotravhar_5));
}

void ProcessMenu_me_cmdpotravhar_0(string sMenu_me_cmdpotravhar_0)
{
  string sMenu_me_cmdpotravhar_0_0 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_0, "Koláèe");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_0_0(sMenu_me_cmdpotravhar_0_0));

  string sMenu_me_cmdpotravhar_0_1 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_0, "Chleba");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_0_1(sMenu_me_cmdpotravhar_0_1));

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_0_0(string sMenu_me_cmdpotravhar_0_0)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_0, "Tøešòovı koláè", "cnrCherryPie", 50, 50, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_0, "Ostruinovı koláè", "cnrBlkberryPie", 50, 50, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_0, "Oøechovı koláè", "cnrPecanPie", 50, 50, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_0, "Jableènı koláè", "cnrApplePie", 50, 50, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_0, "Borùvkovı koláè", "cnrBluberryPie", 50, 50, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_0_1(string sMenu_me_cmdpotravhar_0_1)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_1, "itnı chléb", "cnrRyeBread", 60, 60, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_1, "Rıovı chléb", "cnrRiceBread", 60, 60, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_1, "Pšeniènı chléb", "cnrWheatBread", 60, 60, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_1, "Ovesnı chléb", "cnrOatsBread", 60, 60, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_0_1, "Kukuøiènı chléb", "cnrCornBread", 60, 60, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_1(string sMenu_me_cmdpotravhar_1)
{
  string sMenu_me_cmdpotravhar_1_0 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_1, "Mouky");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_1_0(sMenu_me_cmdpotravhar_1_0));

  string sMenu_me_cmdpotravhar_1_1 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_1, "Mouèky");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_1_1(sMenu_me_cmdpotravhar_1_1));

  string sMenu_me_cmdpotravhar_1_2 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_1, "Sladové obilniny");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_1_2(sMenu_me_cmdpotravhar_1_2));

  string sMenu_me_cmdpotravhar_1_3 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_1, "Praené obilniny");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_1_3(sMenu_me_cmdpotravhar_1_3));

  string sMenu_me_cmdpotravhar_1_4 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_1, "Slady");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_1_4(sMenu_me_cmdpotravhar_1_4));

  string sMenu_me_cmdpotravhar_1_5 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_1, "Kvasnice");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_1_5(sMenu_me_cmdpotravhar_1_5));

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_1_0(string sMenu_me_cmdpotravhar_1_0)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_0, "itná mouka", "cnrRyeFlour", 5, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_0, "Rıové vloèky", "cnrRiceFlour", 5, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_0, "Pšenièná mouka", "cnrWheatFlour", 5, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_0, "Ovesná mouka", "cnrOatsFlour", 5, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_0, "Kukuøièná mouka", "cnrCornFlour", 5, 5, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_0, "Jeèmenná mouka", "cnrBarleyFlour", 5, 5, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_1_1(string sMenu_me_cmdpotravhar_1_1)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_1, "itná mouèka", "cnrRyeMeal", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_1, "Rıová mouèka", "cnrRiceMeal", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_1, "Pšenièná mouèka", "cnrWheatMeal", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_1, "Ovesná mouèka", "cnrOatsMeal", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_1, "Kukuøièná mouèka", "cnrCornMeal", 4, 4, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_1, "Jeèmenná mouka", "cnrBarleyMeal", 4, 4, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_1_2(string sMenu_me_cmdpotravhar_1_2)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_2, "Sladová kukuøice", "cnrCornMalt", 8, 8, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_2, "Sladová pšenice", "cnrWheatMalt", 8, 8, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_2, "Sladová rıe", "cnrRiceMalt", 8, 8, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_2, "Sladové ito", "cnrRyeMalt", 8, 8, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_2, "Sladovı jeèmen", "cnrBarleyMalt", 8, 8, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_2, "Sladovı oves", "cnrOatsMalt", 8, 8, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_1_3(string sMenu_me_cmdpotravhar_1_3)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_3, "Praená kukuøice", "cnrCornRoasted", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_3, "Praená pšenice", "cnrWheatRoasted", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_3, "Praená rıe", "cnrRiceRoasted", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_3, "Praené ito", "cnrRyeRoasted", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_3, "Praenı jeèmen", "cnrBarleyRoasted", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_3, "Praenı oves", "cnrOatsRoasted", 2, 2, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_1_4(string sMenu_me_cmdpotravhar_1_4)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_4, "itnı slad", "cnrRyeWort", 16, 16, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_4, "Rıovı slad", "cnrRiceWort", 16, 16, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_4, "Pšeniènı slad", "cnrWheatWort", 16, 16, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_4, "Ovesnı slad", "cnrOatsWort", 16, 16, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_4, "Kukuøiènı slad", "cnrCornWort", 16, 16, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_4, "Jeèmennı slad", "cnrBarleyWort", 16, 16, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_1_5(string sMenu_me_cmdpotravhar_1_5)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_5, "Pekaøské kvasnice", "cnrYeastBakers", 3, 3, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_1_5, "Pivovarské kvasnice", "cnrYeastBrewers", 3, 3, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_2(string sMenu_me_cmdpotravhar_2)
{
  string sMenu_me_cmdpotravhar_2_0 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_2, "Oleje");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_2_0(sMenu_me_cmdpotravhar_2_0));

  string sMenu_me_cmdpotravhar_2_1 = CnrMerchantAddSubMenu(sMenu_me_cmdpotravhar_2, "Štávy");
  CmdIncrementStackCount(OBJECT_SELF);
  AssignCommand(OBJECT_SELF, ProcessMenu_me_cmdpotravhar_2_1(sMenu_me_cmdpotravhar_2_1));

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_2_0(string sMenu_me_cmdpotravhar_2_0)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_0, "Rıovı olej", "cnrRiceOil", 7, 7, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_0, "Olej z lískovıch oøíškù", "cnrHazelnutOil", 7, 7, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_0, "Olej z oøechovce", "cnrPecanOil", 7, 7, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_0, "Olej z vlašskıch oøechù", "cnrWalnutOil", 7, 7, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_0, "Mandlovı olej", "cnrAlmondOil", 7, 7, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_0, "Kukuøiènı olej", "cnrCornOil", 18, 18, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_0, "Kaštanovı olej", "cnrChestnutOil", 7, 7, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_2_1(string sMenu_me_cmdpotravhar_2_1)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Tøešòová šáva", "cnrCherryJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Šáva z jalovcovıch bobulí", "cnrJuniperJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Ostruinovı šáva", "cnrBlkberryJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Malinová šáva", "cnrRspberryJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Javorovı syrup", "cnrMapleSyrup", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Jableèná šáva", "cnrAppleJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Hroznová šáva", "cnrGrapeJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Brusinková šáva", "cnrCrnberryJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Borùvková šáva", "cnrBluberryJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Bezinková šáva", "cnrEldberryJuice", 30, 30, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_2_1, "Hrušková šáva", "cnrPearJuice", 30, 30, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_3(string sMenu_me_cmdpotravhar_3)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Tøešòová øeka", "cnrbCherryRiver", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Trpaslièí náøez", "cnrbDwarfsSledge", 120, 120, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Temnı drak", "cnrbDarkDragon", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Slad z èarovného obilí", "cnrbWizardsWheat", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Slad èerného rytíøe", "cnrbBlackKnight", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Orèí poslíèek", "cnrbDeadOrc", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Krémovı slad", "cnrbCrackedSkull", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem2(sMenu_me_cmdpotravhar_3, "Jalovcovı leák", "cnrbJumpinJuniper", "cnrbjumpinjunipe", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Hroznové víno", "cnrGrapeFruit", 2, 2, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Bludná wisky", "cnrbWilloWhiskey", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "eleznı kozel", "cnrbIronHammer", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Praseèí ucho", "cnrbPigsEar", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Støíbrná borovièka", "cnrbSilverBuckle", 100, 100, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_3, "Modrá pálivka", "cnrbBlueSword", 120, 120, TRUE, 0, 1);
  CnrMerchantAddItem2(sMenu_me_cmdpotravhar_3, "Zabijácké pivo", "cnrbBrokenKnuckle", "cnrbbrokenknuckl", 100, 100, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_4(string sMenu_me_cmdpotravhar_4)
{
  CnrMerchantAddItem2(sMenu_me_cmdpotravhar_4, "Maso kraba", "Masokraba", "masokraba001", 10, 10, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_4, "Maso zvíøete", "cnrAnimalMeat", 6, 6, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}

void ProcessMenu_me_cmdpotravhar_5(string sMenu_me_cmdpotravhar_5)
{
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_5, "Hlava bezvìrce", "ry_hlvyvr", 35, 35, TRUE, 0, 1);
  CnrMerchantAddItem(sMenu_me_cmdpotravhar_5, "Hlava bezvìrce", "ry_hlvyvr2", 16, 16, TRUE, 0, 1);

  CmdDecrementStackCount(OBJECT_SELF);
}


